name: Feature Request
description: Suggest a feature to be implemented on NoteSkin Selector Remastered
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "What feature you wanted to see in this project"
    validations: