# Bot for closing GitHub issues automatically after a certain period of time
# https://github.com/lee-dohm/no-response

name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          closeComment: >
            **(This is an automated message)**

            This is issue has been opened for 30 days or more without being closed.
            Why you may ask? becuase it's to prevent people who open an issue, state 
            what the issue is. And if they respond will ghost you for 2^1024 years.
          daysUntilClose: 30